name: Publish Docker

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: elgohr/Publish-Docker-Github-Action@v5
              with:
                  name: wujingtao/nodebook
                  username: 601595686@qq.com
                  password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
                  registry: registry.cn-hangzhou.aliyuncs.com
                  tag_names: true